FROM registry.fedoraproject.org/fedora-toolbox:36

# Keep container image for 2 months
LABEL quay.expires-after=8w

# - Add RPM Fusion repositories
# - Install common development tools
# - Install build dependencies for some Rust applications
# - Remove mlocate
RUN dnf install -y \
    https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm \
    && \
    dnf -y distrosync \
    && \
    dnf -y install \
      ImageMagick \
      ShellCheck \
      awscli \
      brotli \
      butane \
      dejavu-sans-fonts \
      dejavu-sans-mono-fonts \
      centpkg \
      copr-cli \
      createrepo_c \
      fbrnch \
      fd-find \
      fedpkg \
      flatpak-builder \
      fzf \
      g++ \
      gcc \
      go \
      graphviz \
      jq \
      make \
      meson \
      minisign \
      mkpasswd \
      npm \
      pandoc \
      pdf-stapler \
      pwgen \
      pylint \
      python3-dateparser \
      ripgrep \
      rpmfusion-free-release \
      rpmfusion-free-release-tainted \
      rpmfusion-nonfree-release \
      rpmfusion-nonfree-release-tainted \
      ruby \
      ruby-devel \
      rubygem-bundler \
      sqlite \
      vim \
      zoxide \
      zsh \
      --exclude=nodejs-docs,nodejs-full-i18n,btrfs-progs,abattis-cantarell-fonts,adobe-source-code-pro-fonts,systemd-networkd,mercurial-py3,mercurial-py2,subversion,dconf,grubby,kpartx,memstrack && \
    dnf -y install \
      openssl-devel \
      perl-FindBin \
      perl-IPC-Cmd \
      perl-File-Compare && \
    dnf -y remove mlocate && \
    dnf clean all

# No need to clear the output as we will never use ZSH as a login shell and
# this clears output when exiting toolboxes.
RUN sed -i '/clear/d' /etc/zlogout
