FROM registry.fedoraproject.org/fedora-toolbox:38

# - Install common development tools
# - Install build dependencies for some Rust applications
# - Remove mlocate
RUN dnf -y distrosync && \
    dnf -y install \
      ImageMagick \
      ShellCheck \
      awscli \
      brotli \
      bind-utils \
      butane \
      centos-packager \
      centpkg \
      copr-cli \
      coreos-installer \
      createrepo_c \
      dejavu-sans-fonts \
      dejavu-sans-mono-fonts \
      fbrnch \
      fd-find \
      fedmod \
      fedpkg \
      flatpak-builder \
      fzf \
      g++ \
      gcc \
      gettext \
      git-absorb \
      git-delta \
      go \
      graphviz \
      hugo \
      ignition-validate \
      inotify-tools \
      intltool \
      jq \
      json-glib-devel \
      just \
      make \
      meson \
      minisign \
      mkpasswd \
      npm \
      pandoc \
      pdf-stapler \
      pwgen \
      pylint \
      python3-dateparser \
      python3-pip \
      python3-rust2rpm \
      qrencode \
      ripgrep \
      ruby \
      ruby-devel \
      rubygem-bundler \
      shfmt \
      socat \
      source-foundry-hack-fonts \
      sqlite \
      vim \
      yamllint \
      yt-dlp \
      zoxide \
      zsh \
      --exclude=nodejs-docs,nodejs-full-i18n,btrfs-progs,abattis-cantarell-fonts,adobe-source-code-pro-fonts,systemd-networkd,mercurial-py3,mercurial-py2,subversion && \
    dnf -y install \
      openssl-devel \
      perl-FindBin \
      perl-IPC-Cmd \
      perl-File-Compare && \
    dnf -y remove mlocate && \
    dnf -y install dnf-plugins-core && \
    dnf clean all

# Setup host-runner script and symlinks
COPY host-runner /usr/local/bin/host-runner
RUN bins=( \
    "firefox" \
    "flatpak" \
    "google-chrome" \
    "htop" \
    "podman" \
    "rpm-ostree" \
    "systemctl" \
    "virsh" \
    "virt-install" \
    "xdg-open" \
    ); \
    for f in "${bins[@]}"; do \
        ln -s host-runner /usr/local/bin/$f;\
    done

# No need to clear the output as we will never use ZSH as a login shell and
# this clears output when exiting toolboxes.
RUN sed -i '/clear/d' /etc/zlogout
