FROM registry.fedoraproject.org/fedora-toolbox:40

# Can not use herdocs here until GitHub workflows move to a newer Ubuntu
# release with a newer buildah:
# - https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/
# - https://github.com/containers/buildah/issues/3474
# COPY google-cloud-sdk.repo /etc/yum.repos.d/google-cloud-sdk.repo

# - Install common development tools
# - Install build dependencies for some Rust applications
# - Install virt-manager and virt-install
# - Install Cloud command line tools (disabled)
# - Remove mlocate
RUN dnf -y distrosync \
    && dnf -y install \
      bind-utils \
      fd-find \
      fzf \
      git-absorb \
      git-delta \
      inotify-tools \
      jq \
      just \
      make \
      minisign \
      mkpasswd \
      pwgen \
      ripgrep \
      skopeo \
      socat \
      sqlite \
      vim \
      zoxide \
      zsh \
    && dnf -y install \
      ShellCheck \
      black \
      copr-cli \
      createrepo_c \
      g++ \
      gcc \
      intltool \
      json-glib-devel \
      meson \
      pylint \
      python3-dateparser \
      python3-pip \
      python3-rust2rpm \
      shfmt \
      source-foundry-hack-fonts \
      yamllint \
    && dnf -y install \
      flatpak-builder \
      --exclude=adobe-source-code-pro-fonts,glib-networking,low-memory-monitor,memstrack,p11-kit-server,pipewire,tpm2-tools,xdg-desktop-portal \
    && dnf -y install \
      fbrnch \
      fedpkg \
      --exclude=podman,btrfs-progs \
    && dnf -y install \
      go \
      --exclude=mercurial,subversion \
    && dnf -y install \
      mkosi \
      --exclude=apt,arch-install-scripts,archlinux-keyring,debian-keyring,logrotate,pacman,zypper \
    && dnf -y install \
      butane \
      coreos-installer \
      ignition-validate \
    && dnf -y install \
      ImageMagick \
      brotli \
      dejavu-sans-fonts \
      dejavu-sans-mono-fonts \
      graphviz \
      hugo \
      npm \
      pandoc \
      pdf-stapler \
      qrencode \
      ruby \
      ruby-devel \
      rubygem-bundler \
      yt-dlp \
      --exclude=adobe-source-code-pro-fonts,logrotate,low-memory-monitor,nodejs-docs,nodejs-full-i18n,pipewire,tracker,tracker-miners,upower,xdg-desktop-portal-gtk \
    && dnf -y install \
      openssl-devel \
      perl-FindBin \
      perl-IPC-Cmd \
      perl-File-Compare \
    && dnf -y install \
      virt-install \
      virt-manager \
      --exclude=libvirt-daemon,libvirt-daemon-config-network,libvirt-daemon-kvm,libvirt-daemon-qemu,passt,pipewire \
    && dnf -y remove mlocate \
    && dnf clean all

# && dnf -y install \
#   awscli \
#   azure-cli \
#   google-cloud-cli \
#   oci-cli \

# ARG DOCTL_URL="https://github.com/digitalocean/doctl/releases/download/v1.104.0/doctl-1.104.0-linux-amd64.tar.gz"
# ARG DOCTL_SHA256SUMS="f758b0c2fb7857db2bd00439155154f2ab8bee71c4f3640f90f64ec35256ca53  doctl-1.104.0-linux-amd64.tar.gz"

# # Manually install doctl
# RUN wget "${DOCTL_URL}" && \
#     echo "${DOCTL_SHA256SUMS}" | sha256sum --check && \
#     tar xf doctl-*-linux-amd64.tar.gz && \
#     rm doctl-*-linux-amd64.tar.gz && \
#     install -o 0 -g 0 -m 755 doctl /usr/local/bin/doctl

# Setup host-runner script and symlinks
COPY host-runner /usr/local/bin/host-runner
RUN bins=( \
    "firefox" \
    "flatpak" \
    "google-chrome" \
    "htop" \
    "podman" \
    "rpm-ostree" \
    "systemctl" \
    "xdg-open" \
    ); \
    for f in "${bins[@]}"; do \
        ln -s host-runner /usr/local/bin/$f;\
    done

# No need to clear the output as we will never use ZSH as a login shell and
# this clears output when exiting toolboxes.
RUN sed -i '/clear/d' /etc/zlogout
