FROM registry.fedoraproject.org/fedora:37 as unzip

RUN dnf -y install unzip && \
    dnf clean all

# From https://developer.hashicorp.com/nomad/downloads
ENV NAME="nomad"
ENV VERSION="1.4.2"
ENV SHA256="6e24efd6dfba0ba2df31347753f615cae4d3632090e68fc90933e51e640f7afc  nomad_1.4.2_linux_amd64.zip"

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

# From https://github.com/hashicorp/nomad-driver-podman/releases
ENV NAME="nomad-driver-podman"
ENV VERSION="0.4.1"
ENV SHA256="64d78edef0ac89980508749383ff5901840f28a537f4c7ec41fae6f596f13f0e  nomad-driver-podman_0.4.1_linux_amd64.zip"

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /nomad .
COPY --from=unzip /nomad-driver-podman .

CMD ["/nomad"]
