FROM registry.fedoraproject.org/fedora:37 as unzip

RUN dnf -y install unzip && \
    dnf clean all

# From https://developer.hashicorp.com/nomad/downloads
ENV NAME="nomad"
ENV VERSION="1.5.0"
ENV SHA256="3f629ca10452f755580d238f95c0844d7ee9d9c3715f54fb4403fc85b219b720  nomad_1.5.0_linux_amd64.zip"

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

# From https://github.com/hashicorp/nomad-driver-podman/releases
ENV NAME="nomad-driver-podman"
ENV VERSION="0.4.1"
ENV SHA256="64d78edef0ac89980508749383ff5901840f28a537f4c7ec41fae6f596f13f0e  nomad-driver-podman_0.4.1_linux_amd64.zip"

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /nomad .
COPY --from=unzip /nomad-driver-podman .

CMD ["/nomad"]
