FROM docker.io/filebrowser/filebrowser:latest as binary

FROM registry.fedoraproject.org/fedora:43

# Remove unneeded packages and remove all SUID/SGID binaries
RUN <<EORUN
set -xeuo pipefail
rm /etc/dnf/protected.d/sudo.conf
rm /usr/share/dnf5/libdnf.conf.d/protect-sudo.conf
sed -i "s/enabled=1/enabled=0/" "/etc/yum.repos.d/fedora-cisco-openh264.repo"
dnf -y remove pam shadow-utils sudo
dnf -y update
dnf clean all
find /usr \( -perm -4000 -o -perm -2000 \) -exec rm -fv {} \;
EORUN

COPY --from=binary /bin/filebrowser /usr/bin/filebrowser

# Run unprivileged
USER 2000:2000

CMD ["/usr/bin/filebrowser"]
