FROM docker.io/filebrowser/filebrowser:latest as binary

FROM registry.fedoraproject.org/fedora:38

# Keep container image for ~6 months
LABEL quay.expires-after=24w

# Remove unneeded packages and remove all SUID/SGID binaries
RUN rm /etc/dnf/protected.d/sudo.conf && \
    dnf -y remove pam shadow-utils sudo && \
    dnf -y update && \
    dnf clean all && \
    find /usr \( -perm -4000 -o -perm -2000 \) -exec rm -fv {} \;

COPY --from=binary /filebrowser /usr/bin/filebrowser

# Run unprivileged
USER 2000:2000

CMD ["/usr/bin/filebrowser"]
