FROM docker.io/filebrowser/filebrowser:latest as binary

FROM registry.fedoraproject.org/fedora-minimal:43

# Remove unneeded packages and remove all SUID/SGID binaries
RUN <<EORUN
set -xeuo pipefail
sed -i "s/enabled=1/enabled=0/" "/etc/yum.repos.d/fedora-cisco-openh264.repo"
dnf -y remove shadow-utils
dnf -y update
dnf clean all
find /usr \( -perm -4000 -o -perm -2000 \) -exec rm -fv {} \;
EORUN

COPY --from=binary /bin/filebrowser /usr/bin/filebrowser

# Run unprivileged
USER 2000:2000

CMD ["/usr/bin/filebrowser"]
