FROM registry.fedoraproject.org/fedora-toolbox:44 as builder

# - Install common tools
# - Install cloud command line tools
# - Remove mlocate
RUN <<EORUN
set -euxo pipefail
sed -i "s/enabled=1/enabled=0/" "/etc/yum.repos.d/fedora-cisco-openh264.repo"
dnf -y update

dnf copr enable -y siosm/rust-git-absorb

dnf -y install \
  git-absorb \
  git-delta \
  host-spawn \
  jq \
  just \
  ripgrep \
  sqlite \
  vim \
  zsh

cat > /etc/yum.repos.d/google-cloud-sdk.repo <<'EOF'
[google-cloud-cli]
name=Google Cloud CLI
baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el9-x86_64
enabled=1
gpgcheck=1
repo_gpgcheck=0
gpgkey=https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
EOF

dnf -y install \
  awscli \
  azure-cli \
  google-cloud-cli \
  hcloud \
  oci-cli
dnf -y remove mlocate
dnf clean all
EORUN

ARG DOCTL_URL="https://github.com/digitalocean/doctl/releases/download/v1.104.0/doctl-1.104.0-linux-amd64.tar.gz"
ARG DOCTL_SHA256SUMS="f758b0c2fb7857db2bd00439155154f2ab8bee71c4f3640f90f64ec35256ca53  doctl-1.104.0-linux-amd64.tar.gz"

# Manually install doctl
RUN <<EORUN
set -euxo pipefail
wget "${DOCTL_URL}"
echo "${DOCTL_SHA256SUMS}" | sha256sum --check
tar xf doctl-*-linux-amd64.tar.gz
rm doctl-*-linux-amd64.tar.gz
install -o 0 -g 0 -m 755 doctl /usr/local/bin/doctl

dnf -y remove mlocate
dnf clean all

# Setup host-spawn symlinks
set -euxo pipefail
bins=(
    "btop"
    "code"
    "codium"
    "firefox"
    "flatpak"
    "htop"
    "podman"
    "rpm-ostree"
    "systemctl"
    "xdg-open"
);
for f in "${bins[@]}"; do
    ln -s /usr/bin/host-spawn /usr/local/bin/$f
done

# No need to clear the output as we will never use ZSH as a login shell and
# this clears output when exiting toolboxes.
sed -i '/clear/d' /etc/zlogout
EORUN

# Rechunk
FROM quay.io/coreos/chunkah AS chunkah
RUN --mount=from=builder,src=/,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
        chunkah build > /run/src/out.ociarchive

# Final image
FROM oci-archive:out.ociarchive
