FROM registry.fedoraproject.org/fedora:37 as unzip

RUN dnf -y install unzip && \
    dnf clean all

# From https://github.com/hashicorp/nomad-driver-podman/releases
ENV NAME="nomad-driver-podman"
ENV VERSION="0.4.1"
ENV SHA256="64d78edef0ac89980508749383ff5901840f28a537f4c7ec41fae6f596f13f0e  nomad-driver-podman_0.4.1_linux_amd64.zip"

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

FROM registry.fedoraproject.org/fedora:36

# Keep container image for ~2 months
LABEL quay.expires-after=8w

RUN dnf -y update && \
    dnf -y install dnf-plugins-core && \
    dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo && \
    dnf -y install nomad && \
    dnf clean all

RUN mkdir --parents /usr/lib/nomad/plugins
COPY --from=unzip /nomad-driver-podman /usr/lib/nomad/plugins/nomad-driver-podman

CMD ["/usr/bin/nomad"]
