FROM registry.fedoraproject.org/fedora-toolbox:40

# - Install common development tools
# - Install all build deps for kdesrc-build (plasma only, no apps)
# - Install extra packages for KDE development
# - Install build deps for Discover development. This will ignore errors
#   encountered during flatpak installation.
# - Remove mlocate
RUN sed -i "s/enabled=1/enabled=0/" /etc/yum.repos.d/fedora-cisco-openh264.repo \
    && dnf -y distrosync \
    && dnf -y install \
      bind-utils \
      fd-find \
      fzf \
      git-absorb \
      git-delta \
      inotify-tools \
      jq \
      just \
      make \
      minisign \
      mkpasswd \
      pwgen \
      ripgrep \
      skopeo \
      socat \
      sqlite \
      vim \
      zoxide \
      zsh \
    && dnf -y install \
      ShellCheck \
      black \
      copr-cli \
      createrepo_c \
      g++ \
      gcc \
      intltool \
      json-glib-devel \
      meson \
      pylint \
      python3-dateparser \
      python3-pip \
      python3-rust2rpm \
      shfmt \
      source-foundry-hack-fonts \
      yamllint \
    && dnf -y install \
      "cmake(Gpgmepp)" \
      "pkgconfig(libcanberra)" \
      "pkgconfig(libnl-3.0)" \
      "pkgconfig(libnl-route-3.0)" \
      "pkgconfig(libnm)" \
      "pkgconfig(libqrencode)" \
      "pkgconfig(xcb-icccm)" \
      "pkgconfig(xext)" \
      "pkgconfig(xkeyboard-config)" \
      "pkgconfig(xxf86vm)" \
      ModemManager-devel \
      bison \
      boost-devel \
      cmake \
      dialog \
      flex \
      giflib-devel \
      gperf \
      gtk3-devel \
      libSM-devel \
      libXfixes-devel \
      libXft-devel \
      libXi-devel \
      libXrender-devel \
      libXtst-devel \
      libattr-devel \
      libepoxy-devel \
      libgcrypt-devel \
      libical-devel \
      libjpeg-devel \
      libqalculate-devel \
      libxkbfile-devel \
      libxslt-devel \
      lm_sensors-devel \
      lmdb-devel \
      mesa-libEGL-devel \
      mesa-libGL-devel \
      mesa-libgbm-devel \
      openssl-devel \
      pam-devel \
      perl-File-Copy \
      perl-FindBin \
      perl-IPC-Cmd \
      perl-JSON-PP \
      perl-YAML-PP \
      perl-autodie \
      pipewire-devel \
      plymouth-devel \
      polkit-devel \
      pulseaudio-libs-devel \
      python3-cairo-devel \
      qt6-qt5compat-devel \
      qt6-qtbase-private-devel \
      qt6-qtbase-static \
      qt6-qtquickcontrols2-devel \
      qt6-qtsensors-devel \
      qt6-qtshadertools-devel \
      qt6-qttools-devel \
      qt6-qttools-static \
      qt6-qtwayland-devel \
      sassc \
      wayland-devel \
      wayland-protocols-devel \
      xcb-util-cursor-devel \
      xcb-util-devel \
      xcb-util-image-devel \
      xcb-util-keysyms-devel \
      xcb-util-keysyms-devel \
      xcb-util-wm-devel \
      xcb-util-wm-devel \
      xdg-desktop-portal-devel \
    && dnf -y install \
      breeze-cursor-theme \
      breeze-icon-theme \
      gdb \
      git-clang-format \
      kdevelop \
      rpm-ostree-devel \
      strace \
    && dnf -y builddep \
      plasma-discover \
    && dnf -y install \
      qcoro-qt6-devel \
      kf6-kiconthemes-devel \
    && dnf -y remove mlocate \
    && dnf clean all

# No need to clear the output as we will never use ZSH as a login shell and
# this clears output when exiting toolboxes.
RUN sed -i '/clear/d' /etc/zlogout
