FROM registry.fedoraproject.org/fedora-toolbox:44 as builder

# - Install common development tools
# - Install all build deps for kdesrc-build (plasma only, no apps)
# - Install extra packages for KDE development
# - Install build deps for Discover development. This will ignore errors
#   encountered during flatpak installation.
# - Remove mlocate
RUN <<EORUN
set -euxo pipefail
sed -i "s/enabled=1/enabled=0/" "/etc/yum.repos.d/fedora-cisco-openh264.repo"
dnf -y update

dnf -y install \
  erofs-utils \
  fd-find \
  git-absorb \
  git-delta \
  host-spawn \
  inotify-tools \
  jq \
  just \
  make \
  ripgrep \
  sqlite \
  vim \
  zoxide \
  zsh

dnf -y install \
  ShellCheck \
  black \
  g++ \
  gcc \
  json-glib-devel \
  meson \
  pylint \
  python3-pip \
  shfmt \
  source-foundry-hack-fonts \
  yamllint

dnf -y install \
  "cmake(Gpgmepp)" \
  "pkgconfig(libcanberra)" \
  "pkgconfig(libnl-3.0)" \
  "pkgconfig(libnl-route-3.0)" \
  "pkgconfig(libnm)" \
  "pkgconfig(libqrencode)" \
  "pkgconfig(xcb-icccm)" \
  "pkgconfig(xext)" \
  "pkgconfig(xkeyboard-config)" \
  "pkgconfig(xxf86vm)" \
  ModemManager-devel \
  bison \
  boost-devel \
  cmake \
  dialog \
  flex \
  giflib-devel \
  gperf \
  gtk3-devel \
  libSM-devel \
  libXfixes-devel \
  libXft-devel \
  libXi-devel \
  libXrender-devel \
  libXtst-devel \
  libattr-devel \
  libepoxy-devel \
  libgcrypt-devel \
  libical-devel \
  libjpeg-devel \
  libqalculate-devel \
  libxkbfile-devel \
  libxslt-devel \
  lm_sensors-devel \
  lmdb-devel \
  mesa-libEGL-devel \
  mesa-libGL-devel \
  mesa-libgbm-devel \
  openssl-devel \
  pam-devel \
  perl-File-Copy \
  perl-FindBin \
  perl-IPC-Cmd \
  perl-JSON-PP \
  perl-YAML-PP \
  perl-autodie \
  pipewire-devel \
  plymouth-devel \
  polkit-devel \
  pulseaudio-libs-devel \
  python3-cairo-devel \
  qt6-assistant \
  qt6-doc \
  qt6-qt5compat-devel \
  qt6-qtbase-private-devel \
  qt6-qtbase-static \
  qt6-qtquickcontrols2-devel \
  qt6-qtsensors-devel \
  qt6-qtshadertools-devel \
  qt6-qttools-devel \
  qt6-qttools-static \
  qt6-qtwayland-devel \
  sassc \
  wayland-devel \
  wayland-protocols-devel \
  xcb-util-cursor-devel \
  xcb-util-devel \
  xcb-util-image-devel \
  xcb-util-keysyms-devel \
  xcb-util-keysyms-devel \
  xcb-util-wm-devel \
  xcb-util-wm-devel \
  xdg-desktop-portal-devel

dnf -y install \
  breeze-cursor-theme \
  breeze-icon-theme \
  gdb \
  git-clang-format \
  kdevelop \
  rpm-ostree-devel \
  strace

dnf -y builddep \
  plasma-discover

dnf -y install \
  qcoro-qt6-devel \
  kf6-kiconthemes-devel

dnf -y remove mlocate
dnf clean all

# Setup host-spawn symlinks
set -euxo pipefail
bins=(
    "btop"
    "code"
    "codium"
    "firefox"
    "flatpak"
    "htop"
    "podman"
    "rpm-ostree"
    "systemctl"
    "xdg-open"
);
for f in "${bins[@]}"; do
    ln -s /usr/bin/host-spawn /usr/local/bin/$f
done

# No need to clear the output as we will never use ZSH as a login shell and
# this clears output when exiting toolboxes.
sed -i '/clear/d' /etc/zlogout
EORUN

# Rechunk
FROM quay.io/coreos/chunkah AS chunkah
RUN --mount=from=builder,src=/,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
        chunkah build > /run/src/out.ociarchive

# Final image
FROM oci-archive:out.ociarchive
