FROM registry.fedoraproject.org/fedora:36 as unzip

# From https://www.consulproject.io/downloads
ENV CONSUL_VERSION="1.12.3"
ENV CONSUL_SHA256="620a47cfba34bdf918b4c3238d22f6318b29403888cfd927c6006a4ac1b1c9f6  consul_1.12.3_linux_amd64.zip"

RUN dnf -y update && \
    dnf -y install unzip && \
    dnf clean all

RUN curl -O "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip"
RUN echo "${CONSUL_SHA256}" | sha256sum --check
RUN unzip consul_${CONSUL_VERSION}_linux_amd64.zip

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /consul .
CMD ["/consul"]
