FROM registry.fedoraproject.org/fedora:36 as unzip

# Keep container image for ~2 months
LABEL quay.expires-after=8w

# From https://www.consulproject.io/downloads
ENV CONSUL_VERSION="1.12.0"
ENV CONSUL_SHA256="109e2077236cae4560b2fa3dce7974ef58d6a7093d72494614d875e5c86e3b2c  consul_1.12.0_linux_amd64.zip"

RUN dnf -y update && \
    dnf -y install unzip && \
    dnf clean all

RUN curl -O "https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip"
RUN echo "${CONSUL_SHA256}" | sha256sum --check
RUN unzip consul_${CONSUL_VERSION}_linux_amd64.zip

FROM scratch
COPY --from=unzip /consul .
CMD ["/consul"]
