FROM registry.fedoraproject.org/fedora:37 as unzip

# From https://developer.hashicorp.com/consul/downloads
ENV NAME="consul"
ENV VERSION="1.14.3"
ENV SHA256="2971959d50fae1aa3f6b624219c85e0a4f34cd7232ea14d77d3cfb05f9ce7b8f  consul_1.14.3_linux_amd64.zip"

RUN dnf -y install unzip && \
    dnf clean all

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /consul .

CMD ["/consul"]
