FROM registry.fedoraproject.org/fedora-toolbox:37

# Keep container image for ~2 months
LABEL quay.expires-after=8w

# - Install common administration tools
# - Ensure that mlocate is removed
RUN dnf -y distrosync && \
    dnf -y install \
      ShellCheck \
      bwm-ng \
      fd-find \
      htop \
      iotop \
      jq \
      mkpasswd \
      pwgen \
      ripgrep \
      shfmt \
      sqlite \
      tree \
      vim \
      wireguard-tools \
      zoxide \
      zsh \
      && \
    dnf -y remove mlocate && \
    dnf clean all

# No need to clear the output as we will never use ZSH as a login shell and
# this clears output when exiting toolboxes.
RUN sed -i '/clear/d' /etc/zlogout
