FROM registry.fedoraproject.org/fedora:39 AS builder

RUN dnf update -y && \
    dnf install -y rust cargo && \
    cargo install bandwhich
RUN mv /root/.cargo/bin/bandwhich /

FROM registry.fedoraproject.org/fedora-toolbox:39

# Copy bandwhich from builder container
COPY --from=builder /bandwhich /usr/local/bin/bandwhich

# - Only install tools that need root access
# - Ensure that mlocate is removed
RUN dnf -y distrosync && \
    dnf -y install \
      bwm-ng \
      htop \
      igt-gpu-tools \
      iotop \
      sqlite \
      wireguard-tools \
      && \
    dnf -y remove mlocate && \
    dnf clean all
