FROM registry.fedoraproject.org/fedora-minimal:43 as builder

RUN <<EORUN
set -xeuo pipefail

sed -i "s/enabled=1/enabled=0/" "/etc/yum.repos.d/fedora-cisco-openh264.repo"
echo -e "[main]\nkeepcache=True" > "/etc/dnf/libdnf5.conf.d/keepcache.conf"

mkdir -p /output

# Install nginx and additional modules
dnf install -y \
    --releasever 43 \
    --forcearch "x86_64" \
    --installroot /output \
    --use-host-config \
    --setopt install_weak_deps=False \
    --nodocs \
    fedora-release-container \
    glibc-minimal-langpack \
    nginx-core \
    nginx-mod-brotli \
    nginx-mod-headers-more \
    nginx-mod-stream

# Manual cleanup of a few packages we don't need until we land:
# https://src.fedoraproject.org/rpms/nginx/pull-request/22
rm -rf /etc/dnf/protected.d/systemd.conf /usr/share/dnf5/libdnf.conf.d/protect-systemd.conf
rpm --root /output --erase --nodeps --noscripts --notriggers --verbose \
    dbus \
    dbus-broker \
    dbus-common \
    expat \
    fedora-gpg-keys \
    fedora-logos-httpd \
    fedora-repos \
    libfdisk \
    libseccomp \
    systemd \
    systemd-pam \
    systemd-shared \
    systemd-sysusers

# List all installed RPMs
rpm -qa --root /output | sort -h

# Remove all SUID/SGID binaries
find /usr \( -perm -4000 -o -perm -2000 \) -exec rm -fv {} \;
EORUN

# Rechunk
FROM quay.io/coreos/chunkah AS chunkah
RUN --mount=from=builder,src=/output,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
        chunkah build > /run/src/out.ociarchive

# Final image
FROM oci-archive:out.ociarchive
USER nginx
CMD ["/usr/sbin/nginx", "-g", "daemon off;error_log /dev/stdout info;"]
