FROM registry.fedoraproject.org/fedora:36

# Keep container image for ~2 months
LABEL quay.expires-after=8w

RUN dnf -y update && \
    dnf -y install nginx && \
    dnf clean all # nocache 2022-09-21

USER nginx
CMD ["/usr/sbin/nginx"]
