FROM registry.fedoraproject.org/fedora:38

# Keep container image for ~3 months
LABEL quay.expires-after=12w

RUN dnf -y update && \
    dnf -y install unbound && \
    dnf clean all

USER unbound
CMD ["/usr/sbin/unbound"]
