FROM registry.fedoraproject.org/fedora-minimal:43 as builder

RUN <<EORUN
set -xeuo pipefail

sed -i "s/enabled=1/enabled=0/" "/etc/yum.repos.d/fedora-cisco-openh264.repo"
echo -e "[main]\nkeepcache=True" > "/etc/dnf/libdnf5.conf.d/keepcache.conf"

mkdir -p /output

# Install unbound
dnf install -y \
    --releasever 43 \
    --forcearch "x86_64" \
    --installroot /output \
    --use-host-config \
    --setopt install_weak_deps=False \
    --nodocs \
    fedora-release-container \
    glibc-minimal-langpack \
    unbound

# Manual cleanup of a few packages we don't need
rpm --root /output --erase --nodeps --noscripts --notriggers --verbose \
    expat \
    fedora-gpg-keys \
    fedora-repos

# List all installed RPMs
rpm -qa --root /output | sort -h

# Remove all SUID/SGID binaries
find /usr \( -perm -4000 -o -perm -2000 \) -exec rm -fv {} \;
EORUN

# Rechunk
FROM quay.io/coreos/chunkah AS chunkah
RUN --mount=from=builder,src=/output,target=/chunkah,ro \
    --mount=type=bind,target=/run/src,rw \
        chunkah build > /run/src/out.ociarchive

# Final image
FROM oci-archive:out.ociarchive
USER unbound
CMD ["/usr/sbin/unbound"]
