FROM registry.fedoraproject.org/fedora:36 as unzip

# Keep container image for ~2 months
LABEL quay.expires-after=8w

# From https://www.vaultproject.io/downloads
ENV VAULT_VERSION="1.11.0"
ENV VAULT_SHA256="00ec42bed75680c440a16d16c196ab07a1012255448de36af709ec19f1c5b957  vault_1.11.0_linux_amd64.zip"

RUN dnf -y update && \
    dnf -y install unzip && \
    dnf clean all

RUN curl -O "https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip"
RUN echo "${VAULT_SHA256}" | sha256sum --check
RUN unzip vault_${VAULT_VERSION}_linux_amd64.zip

FROM scratch
COPY --from=unzip /vault .
CMD ["/vault"]
