FROM registry.fedoraproject.org/fedora:37 as unzip

# From https://developer.hashicorp.com/vault/downloads
ENV NAME="vault"
ENV VERSION="1.12.3"
ENV SHA256="f4825bad06e77687b407eff7423acb9238adfd545d7345f2a0bb9e81b0c4b1eb  vault_1.12.3_linux_amd64.zip"

RUN dnf -y install unzip && \
    dnf clean all

RUN curl -O "https://releases.hashicorp.com/${NAME}/${VERSION}/${NAME}_${VERSION}_linux_amd64.zip"
RUN echo "${SHA256}" | sha256sum --check
RUN unzip "${NAME}_${VERSION}_linux_amd64.zip"

FROM scratch

# Keep container image for ~2 months
LABEL quay.expires-after=8w

COPY --from=unzip /vault .

CMD ["/vault"]
