FROM registry.fedoraproject.org/fedora:38

# Keep container image for ~2 months
LABEL quay.expires-after=8w

RUN dnf -y update && \
    dnf -y install \
      libvirt-daemon \
      libvirt-daemon-config-network \
      libvirt-daemon-driver-interface \
      libvirt-daemon-driver-network \
      libvirt-daemon-driver-nwfilter \
      libvirt-daemon-driver-qemu \
      libvirt-daemon-driver-secret \
      libvirt-daemon-driver-storage-core \
      qemu-kvm \
      virt-install \
    && dnf clean all

RUN systemctl disable \
    console-getty.service \
    dracut-shutdown.service \
    getty@tty1.service \
    gssproxy.service \
    rpc-statd-notify.service \
    rtkit-daemon.service \
    selinux-autorelabel-mark.service \
    systemd-homed-activate.service \
    systemd-homed.service \
    systemd-hwdb-update.service \
    systemd-network-generator.service \
    systemd-oomd.service \
    systemd-remount-fs.service \
    systemd-sysctl.service \
    systemd-udevd.service \
    upower.service

RUN systemctl mask \
    console-getty.service \
    dracut-shutdown.service \
    getty@tty1.service \
    gssproxy.service \
    rpc-statd-notify.service \
    rtkit-daemon.service \
    selinux-autorelabel-mark.service \
    systemd-homed-activate.service \
    systemd-homed.service \
    systemd-hwdb-update.service \
    systemd-network-generator.service \
    systemd-oomd.service \
    systemd-remount-fs.service \
    systemd-sysctl.service \
    systemd-udevd.service \
    upower.service

RUN systemctl enable libvirtd.service

ENTRYPOINT ["/sbin/init"]
