FROM registry.fedoraproject.org/fedora:38

RUN dnf -y update && \
    dnf -y install --nodocs \
      libvirt-daemon \
      libvirt-daemon-config-network \
      libvirt-daemon-driver-interface \
      libvirt-daemon-driver-network \
      libvirt-daemon-driver-nwfilter \
      libvirt-daemon-driver-qemu \
      libvirt-daemon-driver-secret \
      libvirt-daemon-driver-storage-core \
      libvirt-dbus \
      netcat \
      openssh-server \
      procps-ng \
      qemu-kvm \
      virt-install \
    && dnf clean all

RUN rm -rfv \
    /etc/systemd/system/*.wants/ \
    /etc/systemd/user/*.wants/ \
    /usr/lib/systemd/system/*.wants/ \
    /usr/lib/systemd/user/*.wants/

RUN systemctl enable \
    dbus-broker.service \
    libvirtd.service \
    sshd.service \
    systemd-journald.service \
    systemd-tmpfiles-setup.service

RUN echo -e "ListenAddress 127.0.0.1\nPort 2222" > /etc/ssh/sshd_config.d/10-local.conf

ENTRYPOINT ["/sbin/init"]
