FROM registry.fedoraproject.org/fedora-toolbox:40

# - Install common development tools
# - Install texlive packages
# - Remove mlocate
RUN sed -i "s/enabled=1/enabled=0/" /etc/yum.repos.d/fedora-cisco-openh264.repo && \
    dnf -y distrosync && \
    dnf -y install \
      ImageMagick \
      brotli \
      dejavu-sans-fonts \
      dejavu-sans-mono-fonts \
      fd-find \
      fzf \
      graphviz \
      inkscape \
      jq \
      latexmk \
      meson \
      npm \
      pandoc \
      pdf-stapler \
      ripgrep \
      ruby \
      ruby-devel \
      rubygem-bundler \
      texlive \
      texlive-babel-french \
      texlive-bbding \
      texlive-bigfoot \
      texlive-dejavu \
      texlive-fontawesome \
      texlive-minted \
      texlive-textpos \
      vim \
      zoxide \
      zsh \
      --exclude=nodejs-docs,nodejs-full-i18n,btrfs-progs,abattis-cantarell-fonts,adobe-source-code-pro-fonts,systemd-networkd,mercurial-py3,mercurial-py2,subversion,dconf,grubby,kpartx,memstrack && \
    dnf -y remove mlocate && \
    dnf clean all

# No need to clear the output as we will never use ZSH as a login shell and
# this clears output when exiting toolboxes.
RUN sed -i '/clear/d' /etc/zlogout
