FROM registry.fedoraproject.org/fedora-toolbox:40

# - Install some common development tools
# - Install kdesrc-build Perl dependencies
# - Install kdesrc-build and KDE dependencies
# - We do not clean dnf metadata & cache as this will speed up kdesrc-build
#   initial setup
RUN sed -i "s/enabled=1/enabled=0/" /etc/yum.repos.d/fedora-cisco-openh264.repo \
    && dnf -y distrosync \
    && dnf -y install \
      ShellCheck \
      black \
      expat-devel \
      fd-find \
      gdb \
      git-absorb \
      git-clang-format \
      git-delta \
      jq \
      json-glib-devel \
      just \
      ninja-build \
      pylint \
      ripgrep \
      sqlite \
      strace \
      vim \
      yamllint \
      zoxide \
      zsh \
    && dnf -y install \
        git \
        perl \
        perl-IPC-Cmd \
        perl-MD5 \
        perl-FindBin \
    && mkdir -p /usr/src/kde \
    && cd /usr/src/kde/ \
    && git clone https://invent.kde.org/sdk/kdesrc-build.git \
    && cd kdesrc-build \
    && ln -snf /usr/src/kde/kdesrc-build/kdesrc-build /usr/bin/kdesrc-build \
    && kdesrc-build --initial-setup
