name: "Build Nomad image"

permissions: read-all

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    paths:
      - nomad/*
      - .github/workflows/nomad.yml
  schedule:
    - cron:  '0 0 * * MON'

# Prevent multiple workflow runs from racing (mostly for the main branch)
concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  IMAGE_NAME: "nomad"
  REGISTRY: "quay.io/travier"

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.IMAGE_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: latest ${{ github.sha }}
          containerfiles: ${{ env.IMAGE_NAME }}/Containerfile
          layers: false
          oci: true

      - name: Push to Quay.io
        uses: redhat-actions/push-to-registry@v2
        if: (github.event_name == 'push' || github.event_name == 'schedule') && github.ref_name == 'refs/heads/main'
        with:
          username: ${{ secrets.BOT_USERNAME }}
          password: ${{ secrets.BOT_SECRET }}
          image: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          tags: latest ${{ github.sha }}
