name: "Build Nomad (Fedora) image (PRs)"

permissions: read-all

on:
  pull_request:
    branches:
      - main
    paths:
      - nomad-fedora/*
      - .github/workflows/nomad-fedora-pr.yml

env:
  IMAGE_NAME: "nomad-fedora"
  REGISTRY: "quay.io/travier"

jobs:
  build-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.IMAGE_NAME }}
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          containerfiles: ${{ env.IMAGE_NAME }}/Containerfile
          layers: false
          oci: true
